sudo: false
language: php
php:
  - "5.3.3"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "hhvm"
before_install:
  - if [ "$TRAVIS_PHP_VERSION" = "5.3.3" ]; then composer config disable-tls true; composer config secure-http false; fi
install:
  - composer install
script:
  - composer test
